# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.rest.api_manager:
        class: AppBundle\Rest\Api\Manager
        arguments: ['@app.rest.error.manager', '@logger', '@serializer', '@validator', '@app.performance.listener']
    app.database.manager:
        class: AppBundle\Database\Manager
        arguments: ['@doctrine']
    app.rest.error.manager:
        class: AppBundle\Rest\Error\Manager
        arguments: ['@jms_serializer.serializer','@app.performance.listener']
    app.performance.listener:
        class: AppBundle\Events\Listener\PerformanceListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 5000 }
    app.api.key.user.provider:
        class: AppBundle\Rest\Security\ApiKeyUserProvider
        arguments: ['@app.database.manager']
    app.api.key.authenticator:
        class:  AppBundle\Rest\Security\ApiKeyAuthenticator
        arguments: ['@app.rest.error.manager']
        public: false
    app.rest.exception_listener:
        class: AppBundle\Rest\EventListener\RestExceptionListener
        arguments: ['@app.rest.error.manager', '@logger']
        tags:
             - { name: kernel.event_listener, event: kernel.exception }
    app.events_subscriber.pagination_subscriber:
        class: AppBundle\Events\Subscriber\PaginationSubscriber
        tags:
            - { name: kernel.event_subscriber }