<?php

namespace AppBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserController__JMSInjector
{
    public static function inject($container) {
        require_once __DIR__ . '/../proxies/AppBundle-Controller-UserController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('AppBundle\\Controller\\UserController' => array('listAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyb3afb39a_37d2299dd9448dd5d77a179edee6d31ea4c3ee22\__CG__\AppBundle\Controller\UserController();
        $instance->__CGInterception__setLoader($a);
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\UserController', 'formFactory');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('form.factory', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\UserController', 'lexikFilterUpdater');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('lexik_form_filter.query_builder_updater', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\UserController', 'knpPaginator');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('knp_paginator', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\UserController', 'dbM');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('app.database.manager', 1));
        return $instance;
    }
}
